### ISSUE TITLE
Issue with received data after sending the commands

### ISSUE THREAD

**Issue by TinManAkshay** [botletics/Arduino-AT-Command-Library#4] opened 2021-07-12 21:57 UTC
Hi,

I am using this library for the Hardware Serial connection for UART Tx/RX pins on my custom board. I've Ublox NINA W152 module integrated with SAMD51 MCU on a board. 

I am sending the command "AT" and trying to receive the data. It should either receive "OK" or "ERROR", however I am getting this result showing on the Serial monitor:

![image](https://user-images.githubusercontent.com/57913555/125360723-25a61780-e321-11eb-8db3-e76080669100.png)

I do not know where I am going like whether its a matter of a coding or hardware pins. 

Code (.ino file is attached here). Please try to look at it and let me know what are your thoughts on it? I'd appreciate that.

/* This code is an example of how to use the AT command library to
 *  send AT commands (or ASCII commands) to a module via UART (TX/RX)
 *  using software or hardware serial. The commands can be set up to
 *  check for a specified reply from the module as well as a timeout.
 *  
 *  Author: Timothy Woo (botletics.com)
 *  Last Modified: 10/20/2017
 */

#include "ATcommands.h"
#include "wiring_private.h"
#include <SPI.h>
#include <Wire.h>

void setup() {
  Serial.begin(115200);
  while (!Serial);
  
  pinMode(PIN_LORA_PWREN, OUTPUT);
  pinMode(PIN_WIFI_PWREN, OUTPUT);
  pinMode(PIN_WIFI_RESET, OUTPUT);
  digitalWrite(PIN_LORA_PWREN, LOW); //turn off the power to LoRa Module...
  digitalWrite(PIN_WIFI_PWREN, HIGH); //turn onn the power to WiFi module...
  
  WifiReset(LOW, 10); //Resets the pin to LOW for 10ms...

  pinPeripheral(PIN_SERIAL1_RX, PIO_SERCOM_ALT); 
  pinPeripheral(PIN_SERIAL1_TX, PIO_SERCOM_ALT);

  // Serial Port Hardware Serial1
  Serial1.begin(115200);
  delay(1000);
}

void loop() {
  // Nothing here
  //Serial.println("Sending command: AT");
  Serial1.println("AT\r");
  delay(1000);

  if (Serial1.available())
  {
    Serial.println(Serial1.read());
  }
}

void WifiReset(uint8_t pulse, uint16_t duration){
    if (pulse == LOW) {
    digitalWrite(PIN_WIFI_RESET, HIGH);
    delay(10);
    digitalWrite(PIN_WIFI_RESET, LOW);
    delay(duration);
    digitalWrite(PIN_WIFI_RESET, HIGH);
  }
  else if (pulse == HIGH) {
    digitalWrite(PIN_WIFI_RESET, LOW);
    delay(10);
    digitalWrite(PIN_WIFI_RESET, HIGH);
    delay(duration);
    digitalWrite(PIN_WIFI_RESET, LOW);
  }
}

Thanks,
Akshay

**Comment by botletics** [comment] 2021-07-12 22:28
Part of the problem is that you have blocking code; you use a `delay(1000)` after writing "AT" to `Serial1`, which means by the time you actually check for a response from the module, it's too late. Instead, you should set up a timer like `unsigned long timer1 = millis()` and do a check like `if (millis() - timer1 > 1000)` then proceed to send "AT", and have it always otherwise checking for a serial response from `Serial1`

Second problem is that you need to cast the `Serial1.read()` to type "char" so that it prints out properly in the serial monitor.

**Comment by TinManAkshay** [comment] 2021-07-12 23:47
Hi @botletics ,

First, thanks for the quick response. I appreciate it.

I've made changes according to your statement like this:

void loop() {

  String response = "";
  uint16_t timer = millis();
  if(millis() - timer < 1000){
    Serial.println("AT");
    Serial1.println("AT");

    if (Serial1.available()) 
      {
        char c = Serial1.read();
        response = response + c;
      }
    Serial.println(response);
  }
  delay(1000);
}

The result is shown below:

![image](https://user-images.githubusercontent.com/57913555/125369195-addfe900-e330-11eb-82c1-cf44ab2b7681.png)

I am still not getting accurate results.

**Comment by botletics** [comment] 2021-07-13 03:51
Please check the [example sketch](https://github.com/botletics/AT-Command-Library/blob/master/Examples/sendATcommands/sendATcommands.ino) which shows some functions you can use without having to construct the loop yourself.

**Comment by TinManAkshay** [comment] 2021-07-14 22:10
Hi @botletics ,

This is my loop:

void loop() {
  int i=0;
  String response = "";
  uint16_t timer = millis();
  uint16_t timeout = 1000;
  char replybuffer[255];
  Serial1.print("AT\r\n");
  Serial.print("AT\r\n");
  if(millis() - timer < timeout){
    if (Serial1.available()){
        replybuffer[i] = Serial1.read();
        i++;
   }
   int len = strlen(replybuffer);
   replybuffer[len] = '\0';
   Serial.println(replybuffer);
   
   if(strcmp(replybuffer, "OK")==0){
    Serial.println("status received ok");
   }
   
  }
  delay(1000);
}

This loop is similar to what you have done in your example sketch.

Its still not returning "OK" after sending the command AT.

**Comment by botletics** [comment] 2021-07-14 23:38
What I'm saying is you should use the `sendBlindCommand()` or `sendCommand()` functions.

**Comment by TinManAkshay** [comment] 2021-07-15 01:48
I've been trying to implement your functions in the sketch but its not working. I believe SoftwareSerial.h you are using, its for only AVR architectures. My board has a SAMD MCU with Ublox NINA W152 module. So one thing led to another, Hardware Serial (on your sketch) is also not working.

So I am using wiringprivate.h for the Hardware Serial.

**Please check out your code(along with my changes to implement the hardware serial for SAMD):**

#include "ATcommands.h"
//#include <SoftwareSerial.h>

//#define MCU_RX 9 // Remember MCU RX connects to module TX and vice versa
//#define MCU_TX 10
#define RST 40 // MCU pin to control module reset

//SoftwareSerial moduleSS = SoftwareSerial(MCU_RX, MCU_TX); // MCU RX, TX
//SoftwareSerial *moduleSerial = &moduleSS;*/

// Hardware serial is also possible!
// HardwareSerial *moduleSerial = &Serial1;

#if defined(ARDUINO_ARCH_SAMD) && defined(SAMD_FLOW_CONTROL)
#include "wiring_private.h"
Uart SerialAT(&sercom0, 19, 20, SERCOM_RX_PAD_1, UART_TX_PAD_0, 2, 255);
#define AT_BAUD_RATE 115200
#else
#define SerialAT Serial1
#define AT_BAUD_RATE 9600
#endif

ATcommands module = ATcommands(RST, false); // Use "false" if you don't want AT commands with newline, "true" otherwise

void setup() {
  Serial.begin(115200);

  Serial1.begin(9600);
  while(!Serial1)
  
  delay(1000);
  pinMode(PIN_LORA_PWREN, OUTPUT);
  pinMode(PIN_WIFI_PWREN, OUTPUT);
  digitalWrite(PIN_LORA_PWREN, LOW); //turn off the power to LoRa Module...
  digitalWrite(PIN_WIFI_PWREN, HIGH); //turn onn the power to WiFi module...

#if defined(ARDUINO_ARCH_SAMD) && defined(SAMD_FLOW_CONTROL)
  pinPeripheral(19, PIO_SERCOM_ALT);
  pinPeripheral(20, PIO_SERCOM_ALT);
#endif

 // module.begin(*Serial1);

  // Reset module if needed. This example pulses the reset pin low for 10ms.
  // If left out, the pulse duration is 100ms by default.
  module.reset(LOW, 10); // module.reset(HIGH/LOW, pulseDuration)

  // Blindly send command without checking for reply or timeout
  module.sendBlindCommand("AT");
  delay(1000); // May want to include a small delay depending on what module you're using

  // Send command with timeout but without checking for specific response. Will return false if no reply
  if (!module.sendCommand("AT", 1000)) Serial.println(F("Command failed!"));
  delay(1000);

  // If you leave out the timeout value it defaults to 1000ms, which is usually good enough for most commands
  if (!module.sendCommand("AT")) Serial.println(F("Command failed!"));
  delay(1000);

  // Send command with timeout and check if module's response matches the desired
  if (!module.sendCommand("AT", "OK", 1000)) Serial.println(F("Command failed!"));
}

**Comment by botletics** [comment] 2021-07-15 15:36
Default baud rate for NINA-W152 is 115200 I believe, so you should do `Serial1.begin(115200);`

**Comment by TinManAkshay** [comment] 2021-07-15 18:04
I did change: 

![image](https://user-images.githubusercontent.com/57913555/125835766-ffd7f026-2a70-420e-a227-4b5229a1ba99.png)

In the above image, can you please tell if the output after sending "AT" command looks garbage to you? May be I am not printing correctly (or) hardware pins are not working properly, that's why its showing garbage values??

**Comment by botletics** [comment] 2021-07-15 19:04
Have you tried sending commands to it directly from a serial terminal on your computer?

**Comment by TinManAkshay** [comment] 2021-07-15 19:16
Yes I commented out all the code lines inside the loop() and tried sending commands directly from a serial monitor. But its not working either.

1. When I send "AT", I dont receive anything on serial monitor. Serial monitor doesn't hang.
2. When I send like "AT+CGMM" or "AT+CGMR", serial monitor hangs. Then I need to unplug and plug the board in to put it back in a normal mode.

**Comment by botletics** [comment] 2021-07-15 20:55
Try this really simple code that allows you to type AT commands in the serial monitor and get a response from the module:

```
#if defined(ARDUINO_SAMD_ZERO) && defined(SERIAL_PORT_USBVIRTUAL)
  // Required for Serial on Zero based boards
  #define Serial SERIAL_PORT_USBVIRTUAL
#endif

String command, response;

void setup()
{
  Serial.begin(9600); // Use serial monitor at 9600
  Serial1.begin(115200); // Module at 115200 with hardware serial
}

void loop()
{
  // Read serial monitor command
  // Ex: Send "AT" in serial monitor
  if (Serial.available()) {
    command = Serial.readStringUntil('\n'); // Enable newline in serial monitor
    Serial.print("--> "); Serial.println(command); // Debug
    Serial1.print(command); // Send the command to module    
  }

  // Check for response from module
  if (Serial1.available()) {
    response = Serial1.readStringUntil('\n');
    Serial.print("<-- "); Serial.println(response); // Debug
  }
}
```

NOTE: This code assumes you're using the default hardware serial definitions for `Serial1`, which is pins 0 and 1 on Arduino Zero (SAMD21 board)

**Comment by botletics** [comment] 2021-07-15 20:58
Closing this issue because I don't think it's library-related.

**Closed as completed by botletics** 2021-07-15 20:58 UTC

**Comment by TinManAkshay** [comment] 2021-07-15 22:04
Hi,

Can you please answer one last quick question?

Are you using just Rx and Tx lines (or) RTS and CTS are also required for AT commands to function like, may be, they are required to put the module into Command mode?

After integrating your program, I am getting this:

![image](https://user-images.githubusercontent.com/57913555/125863706-0438f253-fc64-4b99-9980-1ef0117cfb69.png)

**Comment by botletics** [comment] 2021-07-15 22:28
I don't actually have the module (I wrote that code without actually using it), but I think you only need TX/RX to talk with it asynchronously.

**Comment by TinManAkshay** [comment] 2021-07-16 17:58
Hi @botletics ,

Thanks so much for helping me out here. I've made few changes to your latest code above and its working. The problem was I couldnt able to print correct status on the Serial monitor, but when I looked at Console Window (s-center application developed by ublox folks), then I was able to see the correct status of every AT command. 

![image](https://user-images.githubusercontent.com/57913555/125989644-f1b41e22-c25b-41a7-8ac0-5937c18a4651.png)

Now I am trying to send commands to connect to my Wifi network. Do you have any documentation for the necessary AT commands for the same which could be helpful for me? If Yes, please do let me know.

Thanks again,
Akshay

**Comment by botletics** [comment] 2021-07-16 18:00
Glad you got it working, but sorry, this is the wrong place for WiFi module questions.

**Comment by TinManAkshay** [comment] 2021-07-19 20:57
Hi @botletics ,

No problem at all. Since I am able to send the commands through Serial monitor and receive the correct status back. Also, I am able to connect my Ublox module to Wifi via AT commands. 

Now what I am trying to do is set the respective AT commands in the code itself (I dont want to send commands via serial monitor anymore). It's sending the AT command, but I am unable to receive any status back. I am not sure if module is receiving the command from the program. Your thoughts? feedback?
